export {createDID} from "./src/createDid"
export {resolveDID} from "./src/resolveDID"
export {dereferenceDID} from "./src/dereferenceDid"
export {updateKey,addVerificationMethod} from "./src/updateDid"
export {deactivateDID} from "./src/deactivateDid"
export * from "./src/types"