export {createDID} from "./src/createDid"
export {resolveDID} from "./src/resolveDID"
export {dereferenceDID} from "./src/dereferenceDid"
export {updateKey} from "./src/updateDid"
export * from "./src/types"